//admin API 


@url= http://localhost:8000/api/v1

POST {{url}}/admin/register
Content-Type: application/json

#Create new admin user
#http://localhost:3000/verify?c=8173706b-6955-41a4-b7b5-ee5ad792af34&email=ram123@gmail.com
Send Request 


{
  "address": "dsaf",
  "confirmPassword": "123123",
  "email": "asdf@gmail.Com ",
  "fName": "asdf",
  "lName": "asdf123",
  "Phone": "234355"

}

#send request for the category 

 

##========== category api

### create new api
Get  {{url}}/category


### create new api

POST   {{url}}/category
Content-Type: application/json

{
"name": "Mobile"
}



### request OTP
POST {{url}}/request-otp
Content-Type: application/json
{
  "email": "asdf@gmail.com",
  "status": "active"
}


### get categorie(s)
PUT  {{url}}/category
Content-Type: application/json

{
"_id": "63f51ebcdd6284350c21e485",
 "status": "inactive",
"name": "mobile"
}

### delete category
DELETE   {{url}}/category/63f51ebcdd6284350c21e485


#### payment methods
POST {{url}}/payment-methods
Content-Type: application/json

{
  
  "name": "paypal",
  "description": " asdf"
}
