//admin API 


@url= http://localhost:8000/api/v1

### Register a new user
POST {{url}}/admin/register
Content-Type: application/json

{
  "fname": "leonal",
  "lname": "Messi",
  "email": "messi123@gmail.com",
  "password": "123",

}


###login
POST {{url}}/admin/login
Content-Type: application/json

{
  
  "email": "messi10@gmail.com ",
  "password": "123123"
  

}

#send request for the category 

 

##========== category api

### create new api
Get  {{url}}/category


### create new api

POST   {{url}}/category
Content-Type: application/json

{
"name": "Mobile"
}



### request OTP
POST {{url}}/request-otp
Content-Type: application/json
{
  "email": "asdf@gmail.com",
  "status": "active"
}


### update categorie(s)
PUT {{url}}/category
Content-Type: application/json

{
"_id": "64788a1353e707462836303d",
 "status": "inactive",
"name": "Clothing Mensss"
}

### delete category
DELETE   {{url}}/category/63f51ebcdd6284350c21e485


#### payment methods
POST {{url}}/payment-methods
Content-Type: application/json

{
  
  "name": "paypal",
  "description": " asdf"
}


#####AWS health check 
get https: 


###Add new products
POST {{url}}/products/new
Content-Type: application/json

{
  "name": "jacket",
  "Qty": "23",
  "price": "323",
  "description": "sdsdf"

}